-- H2-compatible roles and users for tests
CREATE SCHEMA IF NOT EXISTS incidentes_db;
SET SCHEMA incidentes_db;

CREATE TABLE IF NOT EXISTS cat_roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    creado_por VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    actualizado_por VARCHAR(50),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    rol_id INT NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    creado_por VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    actualizado_por VARCHAR(50),
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES cat_roles(id)
);

INSERT INTO cat_roles (nombre, descripcion, creado_por) VALUES
('USER', 'Usuario basico', 'SYSTEM'),
('AGENT', 'Agente', 'SYSTEM'),
('ADMIN', 'Administrador', 'SYSTEM');

INSERT INTO usuarios (usuario, nombre, apellido, correo, contrasena, rol_id, creado_por) VALUES
('admin', 'Administrador', 'Sistema', 'admin@altamira.com', 'admin', 3, 'SYSTEM');

CREATE INDEX IF NOT EXISTS idx_usuarios_usuario ON usuarios(usuario);
CREATE INDEX IF NOT EXISTS idx_usuarios_correo ON usuarios(correo);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol_id ON usuarios(rol_id);

